### ISSUE TITLE
No module named 'torch_explain.models'

### ISSUE THREAD

**Issue by maxheming** [pietrobarbiero/pytorch_explain#6]
I'm running vdem.ipynb and have this issue，in line 19.I have installed  torch_explain.

**Comment by pietrobarbiero** [comment]
Hi @maxheming! Thank you for reporting this issue! The `experiment` folder is a bit outdated as it was designed for the earlier version of the repository. It will be probably removed in the next code revision. In place of this folder, we have started writing tutorials in our documentation [here](https://pytorch-explain.readthedocs.io/en/latest/index.html). This will allow users to have a simple starting point with the minimal code necessary to setup an experiment and it will be much easier to customize. Please let me know if you find the tutorials helpful so that we can keep improving them.
